[colors.bright]
black = "#6272a4"
blue = "#7face2"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.normal]
black = "#21222c"
blue = "#5294e2"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#282C34"
foreground = "#F8F8F2"

[colors.search.focused_match]
background = "#f8f8f2"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Iosevka Nerd Font Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window.padding]
x = 5
y = 5
